### ISSUE TITLE
missing module 

### ISSUE THREAD

**Issue by cmingxu** [nethunteros/punter#1]
python main.py -t baidu.com

Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import subdomains
  File "/Users/kevinxu/Code/python/punter/subdomains.py", line 1, in <module>
    from dnsdumpster import DNSDumpsterAPI
ImportError: No module named dnsdumpster

**Comment by nethunteros** [comment]
Did you install dnsdumpster?
```
pip install -r requirements.txt
```
Or 
```
pip install dnsdumpster
```
It's working for me.

**Comment by cmingxu** [comment]
Yes, have 
```
pip install -r requirements.txt
```
run before

**Comment by acosonic** [comment]
Says Requirement already satisfied: dnsdumpster in
