### ISSUE TITLE
DNS or Subdomain Erro

### ISSUE THREAD

**Issue by advisor25** [nethunteros/punter#9]
Traceback (most recent call last):
  File "main.py", line 11, in <module>
    import subdomains
  File "/root/Downloads/punter/subdomains.py", line 1, in <module>
    from dnsdumpster import DNSDumpsterAPI
  File "/usr/local/lib/python2.7/dist-packages/dnsdumpster/DNSDumpsterAPI.py", line 82
    file=sys.stderr,
        ^
SyntaxError: invalid syntax

------------------------------------------------------

whats the issue here ? someone can point me in right direction ?

**Comment by nethunteros** [comment]
Fixed in https://github.com/nethunteros/punter/commit/39270a2308b021b4e5294101d178207554d6bdaf
